"""Change token_expiry to datetime

Revision ID: 335c12b9b2a1
Revises: db9ad3e873a7
Create Date: 2022-11-20 08:56:12.757550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335c12b9b2a1'
down_revision = 'db9ad3e873a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
