"""add profile_img to user model

Revision ID: ce04a1029d8e
Revises: eaca8a83e762
Create Date: 2022-11-14 20:06:34.632140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce04a1029d8e'
down_revision = 'eaca8a83e762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_img', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_img')
    # ### end Alembic commands ###
